jomsomProject/accounts/urls.py
from django.conf.urls import url
#from django.urls import path
from . import views
# when multiple apps have same views function and access these same
# views we need to create namespace like below
app_name = 'accounts'

urlpatterns = [
    # path('signup/', views.signup, name='signup'),
    # path('login/', views.log_in, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.log_in, name='login'),
    url(r'^logout/$', views.log_out, name='logout'), #don't use logout as view name, coz it gets
    # mixed up with built-in logout()

]

jomsomProject/jomsomProject/urls.py
from django.conf.urls import url, include
#from django.urls import path

from django.contrib import admin
from posts import views

urlpatterns = [
    #path('', views.home, name='home'),
    url(r'^$', views.home, name='home'),
    #url(r'^ghar/', admin.site.urls), #for security reason
    #path('admin/', admin.site.urls), # change r'^admin/' to something little random for security
    url(r'^admin/', admin.site.urls),
    #path('accounts/', include('accounts.urls')),
    url(r'^accounts/', include('accounts.urls')),
    # 1.11 version
    url(r'^posts/', include('posts.urls')),


]

jomsomProject/posts/urls.py
from django.conf.urls import url
#from django.urls import path

from . import views
# when multiple apps have same views function and access these same
# views we need to create namespace like below
app_name = 'posts'

urlpatterns = [
    url(r'^create/$', views.create, name='create'), # new version of url()
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    url(r'^user/(?P<user_id>[0-9]+)', views.postby, name='postby'),
]

jomsomProject/accounts/models.py
from django.db import models

# Create your models here.

jomsomProject/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE) # to link each post to unique User object
    votes_total = models.IntegerField(default=1)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')
    

jomsomProject/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password1']
        if password == request.POST['password2']:
            try:
                user = User.objects.get(username=username)
                return render(request, 'accounts/signup.html', {'error':'Username already exist!'})
            except User.DoesNotExist:
            # it creates and saves new user obj in database
                user = User.objects.create_user(username = username, password = password)
                login(request, user) # to logged in user
                return render(request, 'posts/home.html') ### ** Need success Page here **
        else:
            return render(request, 'accounts/signup.html', {'error':'Passwords didn\'t match'})
    else:
        return render(request, 'accounts/signup.html')

def log_in(request):
    if request.method == 'POST':
        username = request.POST['username'] # request.POST.get('username')
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None: # or if user:
            # maybe inside if user.is_active:
            login(request, user)
            if 'next' in request.POST: # if there is next element, redirect to it
                return redirect(request.POST['next'])
                #return HttpResponseRedirect(reverse('index'))
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error':'Username and/or Password didn\'t match'})
    else:
        return render(request, 'accounts/login.html')

def log_out(request):
    ''' stackoverflow question: Logout GET vs POST?
        need to use POST not GET for logout. If GET, browser like chrome will prefetch
        pages they think you will visit next.(automatic upload and download)
    '''
    if request.method == 'POST':
        logout(request)
        return redirect('home')

jomsomProject/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth.models import User

from .models import Post



# Create your views here.
@login_required # if not logged in, redirect to login.html and add next element in url
# "?next=/posts/create/", this is where we got redirected to login.html and after successful log-in
# we will redirect to /posts/create/ view 
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            #return render(request, 'posts/home.html') #this will display home page but 
            # it will display url as posts/create not home
            # so, we need to redirect to show home url
            return redirect('home') 
        else:
            return render(request, 'posts/create.html', {'error': 'Error: Must include Title and URL'})

    else:
        return render(request, 'posts/create.html')

def home(request):
    posts = Post.objects.order_by('-votes_total') # - for order by decending value
    return render(request, 'posts/home.html', {'posts': posts})

def upvote(request, pk):
    # if method is GET, browser read url and execute it even before hitting enter key
    # So, it ends up executing GET request multiple times 
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home') 

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect('home') 

def postby(request, user_id): # instead of id, could use username but username might change
    posts = Post.objects.filter(author__id=user_id).order_by('-votes_total') # author__id came from User object thru foreign relation ????
    user = User.objects.get(pk=user_id)
    return render(request,'posts/postby.html', {'posts': posts, 'user': user}) 

jomsomProject/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Log in!</h1>
{% if error %}
	{{ error }}
	<br />
	<br />
{% endif %}

<form method="POST" action="{% url 'accounts:login' %}">
	{% csrf_token %}
	<!-- checking if threre is next element in url -->
	{% if request.GET.next %}
		<input type="hidden" name="next" value={{ request.GET.next }} />
	{% endif %}
	Username:
	<br />
	<input type="text" name="username">
	<br />
	Password:
	<br />
	<input type="password" name="password">
	<br />
	<br />
	<input class="btn btn-primary" type="submit" value="Login">
</form>
{% endblock %}

jomsomProject/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign Up!</h1>
{% if error %}
    {{error}}
    <br />
    <br />
{% endif %}

<form method="POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    Username:
    <br />
    <input type="text" name="username">
    <br />
    Password:
    <br />
    <input type="password" name="password1">
    <br />
    Conform Password:
    <br />
    <input type="password" name="password2">
    <br />
    <br />
    <input class="btn btn-primary" type="submit" value="Sign Up">
</form>
{% endblock %}

jomsomProject/posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

<h1>New Post</h1>
{% if error %}
	{{ error }}
	<br />
	<br />
{% endif %}

<form method="POST" action="{% url 'posts:create' %}">
	{% csrf_token %}
	
	Title:
	<br />
	<input type="text" name="title" />
	<br />
	URL:
	<br />
	<input type="text" name="url" />
	<br />
	<br />
	<input  class="btn btn-primary" type="submit" value="Post">
</form>

{% endblock %}

jomsomProject/posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>
<a class="btn btn-primary" href="{% url 'posts:create' %}">New Post</a>

<br />
<br />
{% for post in posts.all %}
	<table>
		<tr>
		<td style="padding-right: 20px; text-align: center;"><a href="#" onclick="document.getElementById('thumbsUp{{ post.id }}').submit()"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a>
			<br/> {{ post.votes_total }}<br/>
			<a href="#" onclick="document.getElementById('thumbsDown{{ post.id }}').submit()"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span></a>
		</td>
		<td><a href="{{ post.url }}">{{ post.title }}</a><br/>{{ post.pub_date_pretty }} by {{ post.author.username }}<br/></td>
		</tr>

	</table>
	<form id="thumbsUp{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
		{% csrf_token %}
		<input type="hidden">
	</form>
	<form id="thumbsDown{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
		{% csrf_token %}
		<input type="hidden">
	</form>

{% endfor %}

{% endblock %}

jomsomProject/posts/templates/posts/postby.html
{% extends 'base.html' %}

{% block content %}
    <h1>Posts by: {{user.username}} </h1>
   
    <br />
    {% for post in posts.all %}
        <table>
            <tr>
                <td style="padding-right: 20px; text-align: center;"><a href="#" onclick="document.getElementById('thumbsUp{{ post.id }}').submit()"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a>
                    <br/> {{ post.votes_total }}<br/>
                    <a href="#" onclick="document.getElementById('thumbsDown{{ post.id }}').submit()"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span></a>
                </td>
                <td>
                    <a href="{{ post.url }}">{{ post.title }}</a><br/>
                    {{ post.pub_date_pretty }} 
                </td>
            </tr>
       </table>
       <!-- with GET method, browser read & execute url even before hitting enter, so it end up executing multiple
           time when use actually hit enter. So, it execute only once need to be POST method
        -->
        <!-- These forms are called by above <a> tag onclick() -->
        <form id="thumbsUp{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
            {% csrf_token %}
            <input type="hidden">
        </form>
        <form id="thumbsDown{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
            {% csrf_token %}
            <input type="hidden">
        </form>
    
    {% endfor %}

{% endblock %}

jomsomProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Jomsom</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
  	<!-- Just an image -->
	<nav class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#blogNav">
    				<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
  				</button>
				<a class="navbar-brand" href="{% url 'home' %}">
    				Jomsom
    			</a>
    		</div>
    		<div class="collapse navbar-collapse" id="blogNav">
    			<ul class="nav navbar-nav navbar-right">
    				{% if user.is_authenticated %}
    				<!-- url of logout can't be like signUp and login because we need POST method
    					and we can't put form inside <a> tag. Solution is as follows
    				-->
    					<li><a href="#" onclick="document.getElementById('logoutForm').submit()">Logout</a></li>
    					<form id="logoutForm" method="POST" action="{% url 'accounts:logout' %}">
    						{% csrf_token %}
    						<input type="hidden">
    					</form>
    				{% else %}
    					<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
    					<li><a href="{% url 'accounts:login' %}">Login</a></li>
    				{% endif %}
    				
      				
    			</ul>
    		</div>
    	</div>
    </nav>
  	<div class="container">
  		{% block content %}
		{% endblock %}
	</div>

	<div>
		{% block footer %}
			Footer <br />
			<li><a href="#">About</a></li>
		{% endblock %}
	</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>